# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-17 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180817_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wish',
            name='name',
            field=models.TextField(),
        ),
    ]
